language: node_js
node_js:
  - 8
  - 10
  - 12
install:
  - npm install -g codecov
jobs:
  include:
    - stage: 'test'
      name: 'Run test'
      script: npm run test
    - stage: 'linting'
      name: 'Check linting'
      script: npm run lint
    - stage: 'Generate coverage report'
      name: 'Checking coverage'
      script: codecov